"""ReportLab PDF report generation for RedactQC."""

from __future__ import annotations

from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def _header_footer(canvas, doc):
    """Draw header and footer on each page."""
    canvas.saveState()
    # Header
    canvas.setFont("Helvetica-Bold", 9)
    canvas.setFillColor(colors.HexColor("#333333"))
    canvas.drawString(inch, letter[1] - 0.5 * inch, "RedactQC Audit Report")
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(
        letter[0] - inch, letter[1] - 0.5 * inch, f"Page {doc.page}"
    )
    # Footer
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.grey)
    canvas.drawString(inch, 0.4 * inch, "CONFIDENTIAL - For internal use only")
    canvas.drawRightString(
        letter[0] - inch, 0.4 * inch, "Generated by RedactQC"
    )
    # Line under header
    canvas.setStrokeColor(colors.HexColor("#cccccc"))
    canvas.line(inch, letter[1] - 0.6 * inch, letter[0] - inch, letter[1] - 0.6 * inch)
    canvas.restoreState()


def generate_pdf(data: dict, output_path: Path) -> None:
    """Generate a professional PDF audit report.

    Args:
        data: Report data from generator._fetch_batch_data().
        output_path: Where to write the PDF.
    """
    batch = data["batch"]
    documents = data["documents"]
    findings_by_doc = data["findings_by_doc"]

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        topMargin=0.9 * inch,
        bottomMargin=0.7 * inch,
        leftMargin=inch,
        rightMargin=inch,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Title"], fontSize=20, spaceAfter=12
    )
    heading_style = ParagraphStyle(
        "SectionHeading", parent=styles["Heading2"], fontSize=14, spaceAfter=8,
        textColor=colors.HexColor("#1a1a1a"),
    )
    subheading_style = ParagraphStyle(
        "SubHeading", parent=styles["Heading3"], fontSize=11, spaceAfter=6,
        textColor=colors.HexColor("#333333"),
    )
    body_style = styles["Normal"]

    elements: list = []

    # ── Title ─────────────────────────────────────────────────────────────
    elements.append(Paragraph("RedactQC Audit Report", title_style))
    elements.append(Spacer(1, 6))

    # ── Executive Summary ─────────────────────────────────────────────────
    elements.append(Paragraph("Executive Summary", heading_style))

    total_findings = sum(d["finding_count"] for d in documents)
    # Count high-confidence findings
    high_conf_count = 0
    for doc_findings in findings_by_doc.values():
        high_conf_count += sum(1 for f in doc_findings if f["confidence"] >= 0.8)

    summary_data = [
        ["Batch Name", batch["name"]],
        ["Scan Date", batch["created_at"]],
        ["Source Path", batch["source_path"]],
        ["Total Documents", str(batch["total_docs"])],
        ["Documents Processed", str(batch["processed_docs"])],
        ["Documents with Findings", str(batch["docs_with_findings"])],
        ["Total Findings", str(total_findings)],
        ["High-Confidence Findings (>= 0.8)", str(high_conf_count)],
    ]
    summary_table = Table(summary_data, colWidths=[2.5 * inch, 4 * inch])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0f0f0")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 16))

    # ── PII Type Breakdown ────────────────────────────────────────────────
    elements.append(Paragraph("PII Type Breakdown", heading_style))

    pii_counts: dict[str, list[float]] = {}
    for doc_findings in findings_by_doc.values():
        for f in doc_findings:
            entry = pii_counts.setdefault(f["pii_type"], [0, 0.0])
            entry[0] += 1
            entry[1] += f["confidence"]

    if pii_counts:
        pii_data = [["PII Type", "Count", "Avg Confidence"]]
        for pii_type in sorted(pii_counts, key=lambda k: pii_counts[k][0], reverse=True):
            count = int(pii_counts[pii_type][0])
            avg = pii_counts[pii_type][1] / count if count > 0 else 0
            pii_data.append([pii_type, str(count), f"{avg:.2f}"])

        pii_table = Table(pii_data, colWidths=[3 * inch, 1.5 * inch, 2 * inch])
        pii_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ALIGN", (1, 0), (-1, -1), "CENTER"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8f8f8")]),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(pii_table)
    else:
        elements.append(Paragraph("No findings recorded.", body_style))

    elements.append(Spacer(1, 16))

    # ── Per-Document Sections ─────────────────────────────────────────────
    elements.append(Paragraph("Document Details", heading_style))

    for doc_info in documents:
        doc_id = doc_info["id"]
        doc_findings = findings_by_doc.get(doc_id, [])

        elements.append(Paragraph(doc_info["filename"], subheading_style))

        meta_text = (
            f"Pages: {doc_info['page_count']} | "
            f"Findings: {doc_info['finding_count']} | "
            f"Status: {doc_info['status']}"
        )
        elements.append(Paragraph(meta_text, body_style))
        elements.append(Spacer(1, 4))

        if doc_findings:
            findings_data = [["Page", "PII Type", "Confidence", "Context"]]
            for f in doc_findings:
                # Truncate context for table display
                ctx = f["context_snippet"][:40]
                if len(f["context_snippet"]) > 40:
                    ctx += "..."
                findings_data.append([
                    str(f["page_number"]),
                    f["pii_type"],
                    f"{f['confidence']:.2f}",
                    ctx,
                ])

            findings_table = Table(
                findings_data,
                colWidths=[0.6 * inch, 1.8 * inch, 1 * inch, 3.1 * inch],
            )
            findings_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#34495e")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("ALIGN", (0, 0), (0, -1), "CENTER"),
                ("ALIGN", (2, 0), (2, -1), "CENTER"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1),
                 [colors.white, colors.HexColor("#f8f8f8")]),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ]))
            elements.append(findings_table)
        else:
            elements.append(Paragraph("<i>No findings for this document.</i>", body_style))

        elements.append(Spacer(1, 12))

    # Build
    doc.build(elements, onFirstPage=_header_footer, onLaterPages=_header_footer)
